### ISSUE TITLE
Credentials.fromJson doesn't support underscored keys

### ISSUE THREAD

**Issue by stevenroose** [dart-lang/oauth2#1]
I don't know the OAuth2 standard, but I seem to find a lot of providers that use underscores in their JSON instead of camel casing.

The `Credentials.fromJson` constructor expects camel casing and doesn't recognize the underscored counterparts.

Is this intended behaviour?

**Comment by stevenroose** [comment]
I just noticed that the `handleAccessTokenResponse` method in the `src/handle_access_token_response.dart` file parses the OAuth response and does support the underscore format. However, that method is not exposed.

I have to do a manual access token request (the AuthorizationGrant flow is not the one I need (Reddit public API)), so I have to build credentials from the token response manually. Exposure of that method or a separate `Credentials.fromAccessTokenResponse` would be very useful.

**Comment by nex3** [comment]
`Credentials.fromJson` isn't a method that interacts with the OAuth2 protocol; it and `Credentials.toJson()` are utility methods designed to make it easy for users to save the user's credentials somewhere and restore them later. The only thing the format is expected to interoperate with is the Dart oauth2 package.

Currently only the authorization grant flow is supported by this package. If you'd like to add a different flow, please feel free, but I'd rather not expose library-internal methods in order to partially support a different flow.
